export const icons = {
  reactJS: "/icons/react.svg",
  primereact: "/icons/primereact.svg",
  mySQL: "/icons/mysql.svg",
  nodeJS: "/icons/nodeJS.svg",
  expressJS: "/icons/express.svg",
  mongoDB: "/icons/mongoDB.svg",
  firebase: "/icons/firebase.svg",
  materialUI: "/icons/materialUI.svg",
  css: "/icons/css.svg",
  git: "/icons/git.svg",
  html: "/icons/html.svg",
  javascript: "/icons/javascript.svg",
  vite: "/icons/vite.svg",
  postgreSQL: "/icons/postgreSQL.svg",
  postman: "/icons/postman.svg",
  jira: "/icons/jira.svg",
  jest: "/icons/jest.svg",
  tailwind: "/icons/tailwind.svg",
  expressWhite: "/icons/express-white.svg",
  mysqlWhite: "/icons/mysql-white.svg",
  quote: "/icons/quote.svg",
};
