export const icons = {
  reactJS: "/src/assets/icons/react.svg",
  primereact: "/src/assets/icons/primereact.svg",
  mySQL: "/src/assets/icons/mysql.svg",
  nodeJS: "/src/assets/icons/nodeJS.svg",
  expressJS: "/src/assets/icons/express.svg",
  mongoDB: "/src/assets/icons/mongodb.svg",
  firebase: "/src/assets/icons/firebase.svg",
  materialUI: "/src/assets/icons/materialUI.svg",
  css: "/src/assets/icons/css.svg",
  git: "/src/assets/icons/git.svg",
  html: "/src/assets/icons/html.svg",
  javascript: "/src/assets/icons/javascript.svg",
  vite: "/src/assets/icons/vite.svg",
  postgreSQL: "/src/assets/icons/postgreSQL.svg",
  postman: "/src/assets/icons/postman.svg",
  jira: "/src/assets/icons/jira.svg",
  jest: "/src/assets/icons/jest.svg",
  tailwind: "/src/assets/icons/tailwind.svg",
};
