export const icons = {
  reactJS: "/public/icons/react.svg",
  primereact: "/public/icons/primereact.svg",
  mySQL: "/public/icons/mysql.svg",
  nodeJS: "/public/icons/nodeJS.svg",
  expressJS: "/public/icons/express.svg",
  mongoDB: "/public/icons/mongodb.svg",
  firebase: "/public/icons/firebase.svg",
  materialUI: "/public/icons/materialUI.svg",
  css: "/public/icons/css.svg",
  git: "/public/icons/git.svg",
  html: "/public/icons/html.svg",
  javascript: "/public/icons/javascript.svg",
  vite: "/public/icons/vite.svg",
  postgreSQL: "/public/icons/postgreSQL.svg",
  postman: "/public/icons/postman.svg",
  jira: "/public/icons/jira.svg",
  jest: "/public/icons/jest.svg",
  tailwind: "/public/icons/tailwind.svg",
  expressWhite: "/public/icons/express-white.svg",
  mysqlWhite: "/public/icons/mysql-white.svg",
  quote: "/public/icons/quote.svg",
};
