export const projects = [
  {
    title: "Business Manager",
    description: "Management system for products, clients, and sales, built with React on the frontend using PrimeReact for styled components, and a backend powered by Node.js, Express, and MySQL. It includes a RESTful API for CRUD operations and external service integration, focusing on modularity and scalability.",
    imagePath: "/images/business-manager.png",
    frontEndRepositoryPath: "https://github.com/IgnacioFleming/management-system-frontend",
    backEndRepositoryPath: "https://github.com/IgnacioFleming/backoffice-backend",
    deploy: "https://management-system-frontend-five.vercel.app",
    stack: ["reactJS", "primereact", "expressJS", "nodeJS", "mySQL"],
  },
  {
    title: "The Office Store",
    description: "Full e-commerce built with React and Node.js. Users can browse products, add them to the cart, and make purchases. Integrated with Stripe for secure payment processing and includes a backend for managing products, orders, and users.",
    imagePath: "/images/the-office-store.png",
    frontEndRepositoryPath: "https://github.com/IgnacioFleming/webapp_ecommerce_frontend",
    backEndRepositoryPath: "https://github.com/IgnacioFleming/app-ecommerce-backend",
    deploy: "https://webapp-ecommerce-frontend.vercel.app",
    stack: ["reactJS", "materialUI", "expressJS", "nodeJS", "mongoDB"],
  },
  {
    title: "Vizcacha Wines",
    description: "An institutional website for a local winery, built with React and styled using Material UI. The site features essential sections and a dynamic contact form integrated with Firebase Firestore to store inquiries. Additionally, a custom Node.js service sends email notifications to the company upon form submission.",
    imagePath: "/images/vizcacha-wines.png",
    frontEndRepositoryPath: "https://github.com/IgnacioFleming/vizcacha-wines",
    deploy: "",
    stack: ["reactJS", "materialUI", "firebase"],
  },
  {
    title: "Serminca",
    description: "A professional website for a mining company, built using React and styled with Material UI. It features an interactive contact form that stores inquiries in Firebase Firestore, along with two embedded Google Maps showing key locations. The email notifications for form submissions are handled by a custom Node.js service.",
    imagePath: "/images/serminca.png",
    frontEndRepositoryPath: "https://github.com/IgnacioFleming/Serminca",
    deploy: "",
    stack: ["reactJS", "materialUI", "firebase"],
  },
];
