const root = "content.projects.cards";
export const projects = [
  {
    title: `${root}.frontend-mentoring.title`,
    description: `${root}.frontend-mentoring.description`,
    imagePath: "/images/mentoring-ecommerce.webp",
    codebasePath: "https://github.com/IgnacioFleming/react-mentoring-ecommerce-ifleming",
    deploy: "https://react-mentoring-ecommerce-ifleming.vercel.app/",
    stack: ["typescript", "reactJS", "zustand", "tanstackQuery"],
  },
  {
    title: `${root}.whatsapp-clone.title`,
    description: `${root}.whatsapp-clone.description`,
    imagePath: "/images/wonder-chat.webp",
    codebasePath: "https://github.com/IgnacioFleming/wonder-chat",
    deploy: "https://wonder-chat-production.up.railway.app",
    stack: ["typescript", "nodeJS", "mongoDB"],
  },
  {
    title: `${root}.business-manager.title`,
    description: `${root}.business-manager.description`,
    imagePath: "/images/business-manager.webp",
    frontEndRepositoryPath: "https://github.com/IgnacioFleming/management-system-frontend",
    backEndRepositoryPath: "https://github.com/IgnacioFleming/backoffice-backend",
    deploy: "https://management-system-frontend-five.vercel.app",
    stack: ["reactJS", "primereact", "expressJS", "nodeJS", "mySQL"],
  },
  {
    title: `${root}.the-office-store.title`,
    description: `${root}.the-office-store.description`,
    imagePath: "/images/the-office-store.webp",
    frontEndRepositoryPath: "https://github.com/IgnacioFleming/webapp_ecommerce_frontend",
    backEndRepositoryPath: "https://github.com/IgnacioFleming/app-ecommerce-backend",
    deploy: "https://webapp-ecommerce-frontend.vercel.app",
    stack: ["reactJS", "materialUI", "expressJS", "nodeJS", "mongoDB"],
  },
  {
    title: `${root}.vizcacha-wines.title`,
    description: `${root}.vizcacha-wines.description`,
    imagePath: "/images/vizcacha-wines.webp",
    codebasePath: "https://github.com/IgnacioFleming/vizcacha-wines",
    deploy: "https://vizcacha-wines.vercel.app",
    stack: ["reactJS", "materialUI", "firebase"],
  },
  // {
  //   title: `${root}.todo-app.title`,
  //   description: `${root}.todo-app.description`,
  //   imagePath: "/images/todo.webp",
  //   codebasePath: "https://github.com/IgnacioFleming/to-do",
  //   deploy: "https://to-do-iota-lilac.vercel.app",
  //   stack: ["typescript", "html", "css"],
  // },
  // {
  //   title: `${root}.serminca.title`,
  //   description: `${root}.serminca.description`,
  //   imagePath: "/images/serminca.webp",
  //   frontEndRepositoryPath: "https://github.com/IgnacioFleming/Serminca",
  //   deploy: "https://serminca.vercel.app",
  //   stack: ["reactJS", "materialUI", "firebase"],
  // },
];
